#!/usr/bin/env bats
# Slice E AC26 / AC27 / AC28 — Codebase-map DUAL_PATH reader.
#
# The codebase-map sub-file is GENERATED by the codebase-map.cli build pipeline
# (Slice C) and written to ~/.claude/db/codebase-map/{hash}/codebase-map.md.
# A user may also have a hand-written manual map at the canonical
# session-memory location (~/.claude/session-memory/{hash}/codebase-map.md).
# During the 30-day DUAL_PATH soak the reader must:
#
#   AC26: When generator output is present → return generator output;
#         the manual file is untouched on disk.
#   AC27: When generator output is absent (rebuild failed / fresh install)
#         AND manual file is present → fall back to manual AND emit one
#         JSONL line at metrics/{session}/codebase-map-divergence.jsonl
#         with source: "codebase-map-fallback".
#   AC28: When BOTH present and content differs → return generator output
#         AND emit one JSONL line source: "codebase-map-divergence" with
#         a content-hash pair (no full content — privacy + size).
#
# bats `run` merges stderr into $output (no --separate-stderr in 1.13).
# All bats tests use grep on $output to assert content, NOT bash
# `[[ ... ]]` glob matching — bats 1.13 silently swallows non-final
# `[[ ]]` failures, so explicit `grep -q || return 1` is the only
# reliable pattern.

setup() {
  BATS_FILE_TMPDIR="$(mktemp -d -t cm-divergence.XXXXXX)"
  TEST_HOME="$BATS_FILE_TMPDIR/home"; mkdir -p "$TEST_HOME"
  export HOME="$TEST_HOME"
  export CLAUDE_CONFIG_DIR="$TEST_HOME/.claude"
  export CLAUDE_SESSION_ID="test-session"
  HASH="abc123"
  GEN_DIR="$CLAUDE_CONFIG_DIR/db/codebase-map/$HASH"
  MAN_DIR="$CLAUDE_CONFIG_DIR/session-memory/$HASH"
  mkdir -p "$GEN_DIR" "$MAN_DIR"
  GEN_FILE="$GEN_DIR/codebase-map.md"
  MAN_FILE="$MAN_DIR/codebase-map.md"
  JSONL="$HOME/.claude/metrics/test-session/codebase-map-divergence.jsonl"
  unset _SESSION_STORE_RESOLVED_BACKEND
  REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"
  source "$REPO_ROOT/hooks/_lib/session-memory-read-split.sh"
}

teardown() { rm -rf "$BATS_FILE_TMPDIR"; }

@test "AC26: reader returns generator output when present" {
  printf '%s\n' '# Codebase Map (generated)' 'auto body sentinel' > "$GEN_FILE"
  printf '%s\n' '# Codebase Map (manual)' 'manual body sentinel' > "$MAN_FILE"
  manual_before=$(cat "$MAN_FILE")
  run session_memory_read_split "$HASH" "codebase-map"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "auto body sentinel"
  ! echo "$output" | grep -q "manual body sentinel"
  # Manual file is untouched on disk.
  [ "$(cat "$MAN_FILE")" = "$manual_before" ]
}

@test "AC27: falls back to manual when generator absent" {
  # No generator file written — only manual.
  printf '%s\n' '# Codebase Map (manual)' 'manual fallback body' > "$MAN_FILE"
  run session_memory_read_split "$HASH" "codebase-map"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "manual fallback body"
  [ -s "$JSONL" ]
  grep -q '"source": "codebase-map-fallback"' "$JSONL"
  grep -q "$HASH" "$JSONL"
}

@test "AC28: emits divergence JSONL when content differs" {
  printf '%s\n' '# Codebase Map (generated)' 'auto-only sentinel' > "$GEN_FILE"
  printf '%s\n' '# Codebase Map (manual)' 'manual-only sentinel' > "$MAN_FILE"
  run session_memory_read_split "$HASH" "codebase-map"
  [ "$status" -eq 0 ]
  # Reader returns the generator output.
  echo "$output" | grep -q "auto-only sentinel"
  # JSONL records the divergence with content-hash pair, NO full content.
  [ -s "$JSONL" ]
  grep -q '"source": "codebase-map-divergence"' "$JSONL"
  grep -q '"content_hash_generator"' "$JSONL"
  grep -q '"content_hash_manual"'    "$JSONL"
  # Privacy: no full content in the JSONL line.
  ! grep -q "auto-only sentinel"   "$JSONL"
  ! grep -q "manual-only sentinel" "$JSONL"
}

@test "AC28-bis: identical content does NOT emit divergence JSONL" {
  printf '%s\n' '# Codebase Map' 'same body' > "$GEN_FILE"
  printf '%s\n' '# Codebase Map' 'same body' > "$MAN_FILE"
  run session_memory_read_split "$HASH" "codebase-map"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "same body"
  if [[ -f "$JSONL" ]]; then
    ! grep -q '"source": "codebase-map-divergence"' "$JSONL"
  fi
}

# ---- Adversarials (Step 2b — greenfield, cap=5) -----------------------

@test "adversarial-boundary: empty generator file is still preferred over manual" {
  # Boundary: gen exists but is 0-byte. The reader must still prefer it
  # (empty == valid generator output, e.g. fresh repo with zero source files).
  : > "$GEN_FILE"  # 0-byte generator file
  printf '%s\n' '# Codebase Map (manual)' 'manual fallback' > "$MAN_FILE"
  run session_memory_read_split "$HASH" "codebase-map"
  [ "$status" -eq 0 ]
  # Output is the empty generator, NOT the manual content.
  ! echo "$output" | grep -q "manual fallback"
  # Both files non-empty differ (empty vs non-empty) → divergence JSONL emitted.
  [ -s "$JSONL" ]
  grep -q '"source": "codebase-map-divergence"' "$JSONL"
}

@test "adversarial-empty: both files absent returns 1 with no JSONL written" {
  # Null/empty: neither generator nor manual file exists. Reader must
  # return 1 cleanly (the helper will fall through to legacy notes.md
  # branch in session_memory_read_split — but no codebase-map JSONL fires).
  run session_memory_read_split "$HASH" "codebase-map"
  [ "$status" -ne 0 ]
  if [[ -f "$JSONL" ]]; then
    # No codebase-map JSONL records on miss-on-both — only the existing
    # session-store-mirror.jsonl branch (legacy notes fallback) writes.
    ! grep -q '"source": "codebase-map-fallback"'   "$JSONL"
    ! grep -q '"source": "codebase-map-divergence"' "$JSONL"
  fi
}

@test "adversarial-error-path: short_hash returns empty string on missing file" {
  # Error-path: codebase_map_short_hash on a non-existent path must NOT
  # crash; it must return the empty string. This protects the divergence
  # emitter from poisoning the JSONL line with a Python traceback.
  source "$REPO_ROOT/hooks/_lib/codebase-map-divergence.sh"
  result="$(codebase_map_short_hash "$BATS_FILE_TMPDIR/no-such-file.md")"
  [ "$result" = "" ]
  # Sanity-pair: hash on a real file IS a 16-char hex string.
  printf 'hello\n' > "$BATS_FILE_TMPDIR/probe.md"
  result2="$(codebase_map_short_hash "$BATS_FILE_TMPDIR/probe.md")"
  [ "${#result2}" -eq 16 ]
  [[ "$result2" =~ ^[0-9a-f]{16}$ ]]
}
